// Chrome may deduplicate a script URL across manifest content-script entries,
// even when they target different worlds. Give MAIN one distinct bundle URL.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const bundle = ['gemini-rpc.js', 'gemini-main.js']
  .map(file => fs.readFileSync(path.join(root, 'src', file), 'utf8')).join('\n');
fs.writeFileSync(path.join(root, 'src/gemini-main.bundle.js'),
  '// Generated by npm run build. Edit gemini-rpc.js / gemini-main.js instead.\n' + bundle);
